name: Districap
description: A new Flutter project.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
      sdk: flutter
  intl: any
  introduction_screen: ^2.1.0
  shared_preferences: ^2.0.11
  cupertino_icons: ^1.0.3
  #flutter_svg: ^0.22.0 # help us to use SVG in our app ^0.22.0
  flutter_svg: ^2.0.7
  provider: ^6.0.5 # for State management
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  google_sign_in: ^6.1.4
  curved_navigation_bar: ^1.0.3
  cloud_firestore: ^4.9.0
  firebase_database: ^10.2.5
  connectivity_plus: ^2.1.0
  equatable: ^2.0.5
  url_launcher: ^6.0.10
  share_plus: ^7.0.2
  image_picker: ^1.0.1
  collection: ^1.15.0
  youtube_player_flutter: ^8.1.2
  firebase_storage: ^11.2.6
  flutter_cached_pdfview: ^0.4.2
  crypto: ^3.0.3
  flutter_markdown: ^0.6.17
  flutter_translate: ^4.0.4
  #translator: ^0.1.7
  flutter_bloc: ^8.1.3
  grouped_list: ^5.1.2
  geolocator: ^9.0.2
  permission_handler: ^10.4.3
  #open_street_map_search_and_pick: ^0.1.0
  geocoding: ^2.1.0
  google_maps_flutter: ^2.4.0
  flutter_typeahead: ^4.6.2
  google_fonts: ^5.1.0
  pdf: ^3.8.1
  open_file: ^3.3.2
  path_provider: ^2.1.0
  mailer: ^6.0.1
  printing: ^5.11.0
  quickalert: ^1.0.1
  flutter_rating_bar: ^4.0.1
  flutter_local_notifications: ^15.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/images/brands/
    - assets/images/bags/
    - assets/icons/
    - assets/fonts/
    - assets/terms_and_policy/
    - android/app/src/main/res/
    - ios/Runner/Assets.xcassets/

  fonts:
    - family: Muli
      fonts:
        - asset: assets/fonts/muli/Muli.ttf
        - asset: assets/fonts/muli/Muli-Bold.ttf
          weight: 700
        - asset: assets/fonts/muli/Muli-ExtraLight.ttf
          weight: 400
    - family: Mulish
      fonts:
        - asset: assets/fonts/Mulish/Mulish-Black.ttf
        - asset: assets/fonts/Mulish/Mulish-Bold.ttf
          weight: 700
        - asset: assets/fonts/Mulish/Mulish-ExtraLightItalic.ttf
          weight: 300

